/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-dstardd
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_DSTARDD_API_H
#define INCLUDED_DSTARDD_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_dstardd_EXPORTS
#define DSTARDD_API __GR_ATTR_EXPORT
#else
#define DSTARDD_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_DSTARDD_API_H */
