/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dstardd_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e8122d375385f99d905bdbba21bc3dbe)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dstardd/dstardd_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <dstardd_decoder_pydoc.h>

void bind_dstardd_decoder(py::module& m)
{

    using dstardd_decoder    = gr::dstardd::dstardd_decoder;


    py::class_<dstardd_decoder, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<dstardd_decoder>>(m, "dstardd_decoder", D(dstardd_decoder))

        .def(py::init(&dstardd_decoder::make),
           D(dstardd_decoder,make)
        )
        



        ;




}








