/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dstardd_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bf35cae9cee93fefce8fd6dc9c473db9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dstardd/dstardd_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <dstardd_encoder_pydoc.h>

void bind_dstardd_encoder(py::module& m)
{

    using dstardd_encoder    = gr::dstardd::dstardd_encoder;


    py::class_<dstardd_encoder, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<dstardd_encoder>>(m, "dstardd_encoder", D(dstardd_encoder))

        .def(py::init(&dstardd_encoder::make),
           D(dstardd_encoder,make)
        )
        



        ;




}








